### ISSUE TITLE
Missing directory when run poetry update

### ISSUE THREAD

**Issue by johnnyp2587** [mattsta/icli#1]
I'm getting the following when I try to run `poetry update`

![image](https://user-images.githubusercontent.com/50849807/180407471-7f7ce312-1c29-4a84-a978-87b53db01b3a.png)

Seems like it's looking for some mutil directory? Can't seem to find where it should go

**Comment by mattsta** [comment]
oops, my mistake. For development I keep some local dependencies in local directories so changes show up right away, but the local dirs made it into the public package files.

Fixed the public package files to point back to public releases down the dependency tree.


Thanks for the report! A fresh pull then `poetry update` should fix it this time.
