### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '0.5'

### ISSUE THREAD

**Issue by jingmca** [mattsta/icli#4]
if positions have "/MYM", it will cause error as title.  because of  
`File "/Users/xxxxx/Downloads/icli/icli/lang.py", line 2092, in run
    mult = int(o.contract.multiplier or 1)
`
o.contract.multiplier maybe '0.5' when contract is MYM. So, I fixed as this,

`                if o.contract.multiplier == "0.5":
                    mult = 0.5
                else:
                    mult = int(o.contract.multiplier or 1)`

**Comment by mattsta** [comment]
oh thanks! that's a good catch.

I have some more commits to push soon and I'll add the multiplier fix everywhere too (the IBKR API provides multipliers as strings, so that's why the `int()` conversion was everywhere, but I just hadn't noticed contract multipiers can also be fractional).
